
services:
  - type: web
    name: movie_app
    runtime: python  # Specify the runtime environment
    region: oregon  # Optional: specify the region
    plan: free  # Optional: specify the plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: MONGO_DB_CONNECTION_URL
        value: "mongodb+srv://dgbuji:PUUf9bWlkKDwK7wa@clusterdaniel.f7onjhj.mongodb.net/"
